#
#JDBC properties - connecting to my database
#
#spring.datasource.url=jdbc:mysql://localhost:3306/video_directory
#spring.datasource.username=root
#spring.datasource.password=localpassword

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video_directory
    username: root
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

    mail:
      host: localhost
      port: 1025
      username: hello
      password: hello

      properties:
        mail:
          smtp:
            ssl:
              trust: "*"
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000