#
#JDBC properties - connecting to my database
#
#spring.datasource.url=jdbc:mysql://localhost:3306/video_directory
#spring.datasource.username=root
#spring.datasource.password=localpassword

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video_directory
    username: root
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true